export interface agdDTO{
  id_Agd:number,
  id_OrdenEnsayo:number,
  hidrogeno:boolean,
  metano:boolean,
  etano:boolean,
  etileno:boolean,
  acetileno:boolean,
  monoxidodeCarbono:boolean,
  dioxidodeCarbono:boolean,
  nitrogeno:boolean,
  oxigeno:boolean,
  gasesTotales:boolean,
  totaldeGasesCombustibles:boolean,
  observaciones:string,
  fechaSubida:string,
  fechaEnsayo:string,
  linkArchivo:string,
}


export interface agdCreacionDTO{
  id_Agd:number,
  id_OrdenEnsayo:number,
  hidrogeno:boolean,
  metano:boolean,
  etano:boolean,
  etileno:boolean,
  acetileno:boolean,
  monoxidodeCarbono:boolean,
  dioxidodeCarbono:boolean,
  nitrogeno:boolean,
  oxigeno:boolean,
  gasesTotales:boolean,
  totaldeGasesCombustibles:boolean,
  observaciones:string,
  fechaSubida:string,
  fechaEnsayo:string,
  linkArchivo:string,
}
