export interface ordenEnsayoDTO{
  id_OrdenEnsayo:number,
  numeroOrden:number,
  id_Equipo:number,
  id_Laboratorio:number,
  emailUsuario:string,
  nombreUsuario:string,
  fechaCreacion:string,
  fechaExtraccion:string,
  fechaFinalizacion:string,
  fechaPedidoExtraccion:string,
  cuba:string,
  temperatura:string,
  observaciones:string,
  tipoAceite:string,
  inhibido:string,
  motivo:string,
  tipoSolicitud:string,
  urgencia:string,
  nombreSector:string,
  pais:string,
  provincia:string,
  estado:string,
  nombreLaboratista:string,
  usuarioLaboratista:string,
  emailLaboratista:string,
  tomaEnsayo:string,
}


export interface ordenEnsayoCreacionDTO{
  id_OrdenEnsayo:number,
  numeroOrden:number,
  id_Equipo:number,
  id_Laboratorio:number,
  emailUsuario:string,
  nombreUsuario:string,
  fechaCreacion:string,
  fechaExtraccion:string,
  fechaFinalizacion:string,
  fechaPedidoExtraccion:string,
  cuba:string,
  temperatura:string,
  observaciones:string,
  tipoAceite:string,
  inhibido:string,
  motivo:string,
  tipoSolicitud:string,
  urgencia:string,
  nombreSector:string,
  pais:string,
  provincia:string,
  estado:string,
  nombreLaboratista:string,
  usuarioLaboratista:string,
  emailLaboratista:string,
   tomaEnsayo:string,
}

export interface ordenEnsayoVistaCreadorDTO{
  id_OrdenEnsayo:number,
  numeroOrden:number,
  equipo:string,
  laboratorio:string,
  usuario:string,
  fechaCreacion:string,
  nombreSector:string,
  estado:string,
  usuarioLaboratista:string,
}
export interface ordenEnsayoVistaLaboratistaDTO{
  id_OrdenEnsayo:number,
  numeroOrden:number,
  equipo:string,
  usuario:string,
  fechaCreacion:string,
  fechaExtraccion:string,
  fechaFinalizacion:string,
  nombreSector:string,
  estado:string,
 
}

export interface ensayosRealizarDTO{
lista:string[],
id_Ensayo:number,
}